export type ExploreMode = "service" | "material";

export type ServiceCategoryId =
  | "3d-printing"
  | "cnc"
  | "laser-cutting"
  | "welding"
  | "bending"
  | "coating"
  | "woodwork";

export type MaterialCategoryId =
  | "metal"
  | "wood"
  | "acrylic"
  | "fabric"
  | "leather"
  | "etc";

export type CategoryId = ServiceCategoryId | MaterialCategoryId;

export interface CategoryOption {
  id: CategoryId;
  label: string;
  hint: string;
}

export interface Store {
  id: string;
  type: ExploreMode;
  categories: CategoryId[];
  name: string;
  area: string;
  address?: string;
  lat?: number;
  lng?: number;
  phone?: string;
  extraContact?: string;
  description?: string;
  fileGuide?: string;
  orderGuide?: string;
  review?: string;
  memo?: string;
  tags: string[];
  verifiedAt?: string;
  isVisible: boolean;
}

export interface PendingStore {
  name: string;
  area: string;
  phone?: string;
  reason: string;
}

export const modeCopy: Record<
  ExploreMode,
  {
    label: string;
    title: string;
    caption: string;
  }
> = {
  service: {
    label: "작업 맡기기",
    title: "작업 방식으로 업체 찾기",
    caption: "파일 형식, 의뢰 방법, 실제 사용 메모를 중심으로 정리했습니다.",
  },
  material: {
    label: "재료 사기",
    title: "재료 종류로 재료상 찾기",
    caption: "필요한 재료와 구매 전 확인할 내용을 중심으로 봅니다.",
  },
};

export const serviceCategories: CategoryOption[] = [
  { id: "3d-printing", label: "3D프린팅", hint: "출력 제작" },
  { id: "cnc", label: "CNC", hint: "정밀 절삭" },
  { id: "laser-cutting", label: "레이저커팅", hint: "판재 절단" },
  { id: "welding", label: "용접", hint: "금속 접합" },
  { id: "bending", label: "벤딩", hint: "금속 굽힘" },
  { id: "coating", label: "도장", hint: "표면 마감" },
  { id: "woodwork", label: "목공", hint: "목재 제작" },
];

export const materialCategories: CategoryOption[] = [
  { id: "metal", label: "금속", hint: "판, 봉, 파이프" },
  { id: "wood", label: "목재", hint: "원목, 무늬목" },
  { id: "acrylic", label: "아크릴", hint: "아크릴, 플라스틱" },
  { id: "fabric", label: "천", hint: "패브릭, 원단" },
  { id: "leather", label: "가죽", hint: "가죽, 부자재" },
  { id: "etc", label: "기타", hint: "볼트, 전기, 자석" },
];

export const allCategories = [...serviceCategories, ...materialCategories];

export const stores: Store[] = [
  {
    id: "atelier-fl",
    type: "material",
    categories: ["leather"],
    name: "가죽공방 atelier fl",
    area: "성수",
    address: "서울시 성동구 상원4길 9, 3층",
    phone: "070-4188-2635",
    extraContact: "카카오톡 @아뜰리에에프엘",
    description: "가죽 작업 상담과 방문 상담이 가능한 공방",
    memo: "전화 또는 카카오톡으로 먼저 상담한 뒤 방문하는 흐름이 자연스럽습니다.",
    tags: ["상담 가능", "가죽", "방문 상담"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "samgu-woodwork",
    type: "service",
    categories: ["woodwork"],
    name: "삼구나무공방",
    area: "정릉",
    address: "서울특별시 성북구 정릉로26길 6-23 1층",
    phone: "010-4657-2000",
    description: "가구 주문 제작과 목공 수업을 함께 운영하는 목공방",
    memo: "주문 제작과 수업 일정이 함께 운영돼 방문 전 연락이 안전합니다.",
    tags: ["목공", "가구 주문 제작", "원데이 클래스"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "seongjin-cnc-bending",
    type: "service",
    categories: ["cnc", "bending"],
    name: "성진 cnc 벤딩",
    area: "을지로",
    address: "서울특별시 중구 창경궁로5길 29",
    phone: "010-7760-7417",
    description: "CNC 벤딩 작업 문의 가능",
    fileGuide: "도면 또는 치수 기준 자료가 있으면 상담이 빠릅니다.",
    orderGuide: "전화로 가능 여부를 먼저 확인한 뒤 방문하는 방식이 좋습니다.",
    review: "벤딩이 필요한 작업에서 우선 검토할 수 있는 업체입니다.",
    memo: "벤딩이 필요한 작업에서 우선 검토할 수 있는 업체입니다.",
    tags: ["소량 가능", "벤딩", "CNC"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "shinjin-bending",
    type: "service",
    categories: ["bending"],
    name: "신진벤딩",
    area: "을지로",
    address: "서울특별시 중구 창경궁로5길 17",
    description: "금속 프레임과 판재를 벤딩하는 을지로 벤딩 작업 업체",
    orderGuide: "곡률과 길이, 수량을 정리한 도면이나 샘플을 먼저 보여주면 상담이 빠릅니다.",
    memo: "체어 프레임과 같이 반복 곡률이 필요한 작업에서 참고할 수 있는 벤딩 업체로 정리했습니다.",
    tags: ["벤딩", "을지로", "금속 프레임"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "yeongdong-laser",
    type: "service",
    categories: ["laser-cutting"],
    name: "영동레이져땜",
    area: "종로",
    phone: "010-9251-5997",
    description: "쥬얼리 외 큰 물건도 레이저 작업 문의 가능",
    memo: "은땜도 올려서 레이저 작업이 가능하다고 들었고, 현금 결제 기준으로 메모되어 있습니다.",
    tags: ["소량 가능", "레이저", "현금 필수"],
    verifiedAt: "2026-05-30",
    isVisible: false,
  },
  {
    id: "petit-plating",
    type: "service",
    categories: ["coating"],
    name: "쁘띠도금",
    area: "종로",
    address: "서울특별시 종로구 돈화문로 48 2층",
    phone: "02-745-6624",
    description: "도금 및 표면 마감 작업",
    fileGuide: "마감하려는 재료, 색상, 수량을 미리 정리해 가는 것이 좋습니다.",
    orderGuide: "작업물 상태와 원하는 마감 기준을 전화로 먼저 설명하세요.",
    review: "작업 퀄리티가 좋다는 메모가 남아 있습니다.",
    memo: "작업 퀄리티가 좋다는 메모가 남아 있습니다.",
    tags: ["도장", "마감", "추천"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "juju-laser",
    type: "service",
    categories: ["laser-cutting"],
    name: "주주레이저",
    area: "종로",
    phone: "010-7676-1753",
    description: "레이저 작업 문의 가능",
    memo: "토요일에도 연다는 메모가 있어 급한 일정에서 보기 좋습니다.",
    tags: ["레이저", "토요일 영업", "소량 가능"],
    verifiedAt: "2026-05-30",
    isVisible: false,
  },
  {
    id: "samwon-powder-coating",
    type: "service",
    categories: ["coating"],
    name: "삼원분체도장",
    area: "성수",
    address: "서울특별시 성동구 아차산로15길 47-38",
    phone: "02-461-9918",
    description: "분체도장과 각종 표면 마감을 맡길 수 있는 도장 업체",
    memo: "공개 디렉터리에는 47-24가 함께 보여 현재 방문 전 한 번 더 확인하는 편이 안전합니다.",
    tags: ["분체도장", "표면 마감", "도장"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "jeongseong-special-coating",
    type: "service",
    categories: ["coating"],
    name: "정성특수도장",
    area: "문래",
    address: "서울특별시 영등포구 경인로78길 10",
    phone: "02-2637-9594",
    description: "분체, 소부, 우레탄, 에폭시 계열 작업을 하는 특수도장 업체",
    memo: "원하는 마감 방식과 색상, 수량을 먼저 정리해 두면 상담이 빠릅니다.",
    tags: ["도장", "분체도장", "에폭시"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "hana-computer-precision-engraving",
    type: "service",
    categories: ["cnc"],
    name: "하나컴퓨터정밀조각",
    area: "을지로",
    address: "서울특별시 중구 창경궁로 67-6 1층",
    phone: "02-2265-7763",
    description: "개인 소량부터 대응 가능한 CNC 조각 업체",
    memo: "정밀하지 않은 작업도 가능한 편이지만 일정에 따라 달라질 수 있어 먼저 문의하는 편이 좋습니다.",
    tags: ["CNC", "조각", "소량 가능"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "seolsan-industries",
    type: "service",
    categories: ["coating"],
    name: "설산실업",
    area: "영등포",
    address: "서울특별시 영등포구 선유로 176",
    phone: "02-2637-2358",
    description: "도장 및 기타 피막처리 계열 작업이 가능한 업체",
    memo: "문래권 도장 업체로 분류해 두기 좋은 곳입니다.",
    tags: ["도장", "피막처리", "영등포"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "seowon-cnc",
    type: "service",
    categories: ["cnc"],
    name: "서원씨앤씨",
    area: "봉천",
    address: "서울특별시 관악구 관악로 298",
    phone: "1661-5870",
    extraContact: "010-5217-3178",
    description: "CNC 가공 중심으로 상담 가능한 제작 업체",
    memo: "도면 파일과 치수 기준을 함께 전달하면 견적 확인이 수월합니다.",
    tags: ["CNC", "가공", "도면 상담"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "dizfactree",
    type: "service",
    categories: ["laser-cutting"],
    name: "디즈팩트리",
    area: "사당",
    address: "서울특별시 동작구 동작대로13길 17 나동 1층",
    phone: "02-6369-1123",
    extraContact: "010-5126-6369",
    description: "레이저커팅과 디지털 제작 상담이 가능한 공방형 제작소",
    memo: "장비 예약이나 가능 공정이 있어 사전 연락 후 방문하는 흐름이 좋습니다.",
    tags: ["레이저커팅", "제작", "공방"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "top-plus",
    type: "service",
    categories: ["3d-printing"],
    name: "탑플러스",
    area: "종로",
    address: "서울특별시 종로구 율곡로10길 105 1층 128호",
    phone: "0507-1328-2903",
    description: "주얼리 출력 계열의 3D 프린팅과 CAD 출력 상담이 가능한 업체",
    memo: "왁스출력, RP출력 계열 문의처로 정리해 두기 좋습니다.",
    tags: ["3D프린팅", "왁스출력", "CAD 출력"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "changsin-etching",
    type: "service",
    categories: ["cnc"],
    name: "창신부식",
    area: "종로",
    address: "서울특별시 종로구 돈화문로8길 15",
    description: "황동과 동판 계열 판재에 부식 가공과 조각 패턴 작업을 맡길 수 있는 업체",
    orderGuide: "선 두께와 남길 면, 식각 깊이를 도면이나 샘플로 정리해 가면 상담이 수월합니다.",
    memo: "얇은 판재에 문자나 패턴을 정밀하게 넣는 작업처로 메모되어 있습니다.",
    tags: ["부식", "에칭", "조각", "황동"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "3dpro",
    type: "service",
    categories: ["3d-printing"],
    name: "3D프로",
    area: "영등포",
    address: "서울특별시 영등포구 신길로39길 21 3D프로 건물 2층",
    phone: "02-844-6856",
    extraContact: "3dpro@3dprocess.co.kr",
    description: "3D프린팅 출력 대행과 시제품 제작 상담을 진행하는 3D프린팅 업체",
    fileGuide: "STL, OBJ, STEP 같은 3D 파일과 사용 용도를 함께 전달하면 견적 상담이 빠릅니다.",
    memo: "사이트 기준으로 출력 대행과 시제품 제작 문의를 받는 업체로 확인했습니다.",
    tags: ["3D프린팅", "출력 대행", "시제품 제작"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "myeongjin-sibori",
    type: "service",
    categories: ["bending"],
    name: "명진시보리",
    area: "을지로",
    address: "서울특별시 중구 을지로15길 16-6",
    phone: "02-2277-9865",
    description: "금속 시보리와 성형 가공을 맡길 수 있는 업체",
    memo: "동판이나 적동처럼 재질에 따라 가격 차이가 커서 치수와 재질을 먼저 공유하는 편이 좋습니다.",
    tags: ["시보리", "금속 성형", "벤딩"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "buheung-precision",
    type: "service",
    categories: ["cnc"],
    name: "부흥정밀",
    area: "을지로",
    address: "서울특별시 중구 을지로19길 10",
    phone: "02-2273-7644",
    description: "선반 밀링과 기어 가공 계열 문의가 가능한 금속 가공 업체",
    memo: "세운맵에는 인테리어 부품, 선반밀링, 기어가공, 아크릴가공으로 소개되어 있습니다.",
    tags: ["선반밀링", "기어가공", "금속가공"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "migwang-crafts",
    type: "service",
    categories: ["woodwork"],
    name: "미광공예사",
    area: "을지로",
    address: "서울특별시 중구 을지로7가 23-4",
    phone: "02-2235-5273",
    description: "로구로와 목선반 계열 상담이 가능한 공예사",
    memo: "사용자 제보로는 휴대폰 010-3714-5273도 함께 전달받았습니다.",
    tags: ["목선반", "로구로", "공예"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "woodist",
    type: "service",
    categories: ["woodwork"],
    name: "Woodist",
    area: "연희",
    address: "서울특별시 서대문구 성산로 306 102호",
    phone: "010-4708-7282",
    description: "작업용 목공과 수업을 함께 운영하는 연희동 목공방",
    memo: "연희동 기준으로 목공 제작과 클래스 문의처로 정리했습니다.",
    tags: ["목공", "주문 제작", "클래스"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "chromeworld",
    type: "service",
    categories: ["coating"],
    name: "크롬월드",
    area: "김포",
    address: "경기도 김포시 대곶면 소래로41번길 66-73",
    phone: "031-984-3472",
    extraContact: "070-7781-3433",
    description: "크롬도금과 진공증착 계열의 표면 마감 작업 업체",
    memo: "서울권은 아니지만 도금 업체로 자주 언급돼 함께 정리했습니다.",
    tags: ["도금", "크롬", "표면 마감"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "seongbuk-creative-lab",
    type: "service",
    categories: ["laser-cutting"],
    name: "성북 창작소",
    area: "성북",
    address: "서울특별시 성북구 오패산로1길 57",
    phone: "070-8844-6669",
    extraContact: "02-941-9468",
    description: "레이저커팅기와 3D프린터를 활용할 수 있는 성북구 메이커스페이스",
    memo: "구청 운영 공간이라 예약 후 이용하는 방식이 기본입니다.",
    tags: ["레이저커팅", "메이커스페이스", "예약제"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "sy-laser",
    type: "service",
    categories: ["laser-cutting"],
    name: "에스와이레이저",
    area: "동대문",
    address: "서울특별시 동대문구 무학로32길 5",
    phone: "02-926-8628",
    extraContact: "02-927-9290",
    description: "금속 레이저 가공과 절단 작업을 맡길 수 있는 레이저 가공 업체",
    memo: "용두동 기준 레이저 가공 문의처로 정리했습니다.",
    tags: ["레이저커팅", "금속가공", "절단"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "kookmin-sangsang-workshop",
    type: "service",
    categories: ["cnc"],
    name: "국민대 상상공방",
    area: "정릉",
    address: "서울특별시 성북구 정릉로 77 국민대학교 조형대학",
    phone: "02-910-4583",
    description: "국민대 조형대학 내 CNC 라우터를 포함한 디지털 제작 실습 공간",
    memo: "학교 실습 공간이라 일반 업체와 달리 예약과 안전교육 기준을 먼저 확인해야 합니다.",
    tags: ["CNC", "학교 실습실", "예약제"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "acrylic-choika-laser",
    type: "service",
    categories: ["laser-cutting"],
    name: "아크릴최가",
    area: "을지로",
    address: "서울특별시 중구 마른내로 79 세운 푸르지오 헤리시티 B108호",
    phone: "02-2274-8404",
    extraContact: "02-2274-8405",
    description: "아크릴 절단과 가공 작업을 맡길 수 있는 레이저커팅 문의처",
    memo: "재료 탭의 아크릴 항목과 별도로, 가공 의뢰용으로 레이저커팅 분류에도 함께 넣었습니다.",
    tags: ["레이저커팅", "아크릴 가공", "절단"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "samhwan-metal",
    type: "service",
    categories: ["welding"],
    name: "삼환금속",
    area: "을지로",
    address: "서울특별시 중구 창경궁로5길 19",
    description: "금속 프레임과 구조물을 용접 조립하는 을지로 금속 가공 업체",
    orderGuide: "용접 포인트와 조립 순서를 표시한 도면이 있으면 현장 상담이 수월합니다.",
    memo: "벤딩된 파이프나 절곡 부품을 최종 프레임으로 묶는 용접 작업처로 메모되어 있습니다.",
    tags: ["용접", "을지로", "프레임 조립"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "daeseong-materials",
    type: "material",
    categories: ["metal"],
    name: "대성재료상사",
    area: "종로",
    address: "서울특별시 종로구 돈화문로10가길 7",
    phone: "02-762-3808",
    description: "금속 재료 구매처",
    orderGuide: "구매하려는 재료명과 규격을 적어두고 방문하면 빠릅니다.",
    review: "대진보다 저렴하다는 메모가 남아 있습니다.",
    memo: "대진보다 저렴하다는 메모가 남아 있습니다.",
    tags: ["재료 구매 가능", "금속"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "eun-segye",
    type: "material",
    categories: ["metal"],
    name: "은세계",
    area: "종로",
    address: "서울특별시 종로구 돈화문로5가길 1 피카디리플러스 303호",
    phone: "02-747-3371",
    description: "은 관련 재료 구매 가능",
    orderGuide: "은 재료의 단가와 중량 기준을 현장에서 확인하는 것이 좋습니다.",
    review: "은 구매 가격은 다소 높다는 메모가 있습니다.",
    memo: "은 구매 가격은 다소 높다는 메모가 있습니다.",
    tags: ["금속", "은", "재료 구매 가능"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "daejin-materials",
    type: "material",
    categories: ["metal", "etc"],
    name: "대진재료사",
    area: "종로",
    address: "서울특별시 종로구 묘동 99-1",
    phone: "02-766-0985",
    description: "재료 종류가 넓은 재료상",
    orderGuide: "정확한 재료명을 모를 때도 사진이나 샘플을 가져가면 도움이 됩니다.",
    review: "거의 모든 재료를 다루고, 은을 팔 때도 참고할 수 있다는 메모가 있습니다.",
    memo: "거의 모든 재료를 다루고, 은을 팔 때도 참고할 수 있다는 메모가 있습니다.",
    tags: ["재료 구매 가능", "금속", "기타 재료"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "daedeok-metal",
    type: "material",
    categories: ["metal"],
    name: "대덕메탈",
    area: "을지로",
    address: "서울특별시 중구 을지로15길 20",
    phone: "02-2274-2323",
    description: "동판 구매가 가능한 금속 재료상",
    orderGuide: "동판 두께와 크기를 먼저 정리해 문의하세요.",
    review: "동판이 필요할 때 우선 확인할 만한 곳입니다.",
    memo: "동판이 필요할 때 우선 확인할 만한 곳입니다.",
    tags: ["금속", "동판", "재료 구매 가능"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "gaya-metal",
    type: "material",
    categories: ["metal"],
    name: "가야금속",
    area: "을지로",
    address: "서울특별시 중구 을지로15길 24",
    phone: "02-2263-7788",
    description: "파이프와 봉 재료를 찾기 좋은 금속상",
    orderGuide: "파이프, 봉의 지름과 길이를 미리 적어두고 문의하세요.",
    review: "파이프와 봉 메모가 선명하게 남아 있습니다.",
    memo: "파이프와 봉 메모가 선명하게 남아 있습니다.",
    tags: ["금속", "파이프", "봉"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "seoul-magnet",
    type: "material",
    categories: ["etc"],
    name: "서울자석",
    area: "을지로",
    address: "서울특별시 종로구 청계천로 133",
    phone: "02-2279-0445",
    description: "자석을 중심으로 찾는 부자재 상점",
    orderGuide: "자석 크기와 흡착력을 기준으로 문의하는 것이 좋습니다.",
    review: "자석이 필요할 때 바로 떠올릴 수 있는 곳으로 메모되어 있습니다.",
    memo: "자석이 필요할 때 바로 떠올릴 수 있는 곳으로 메모되어 있습니다.",
    tags: ["기타", "자석", "재료 구매 가능"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "hanil-lighting",
    type: "material",
    categories: ["etc"],
    name: "한일조명",
    area: "을지로",
    address: "서울특별시 종로구 청계천로 159 세운상가 1층 라열 118호",
    phone: "02-2263-1646",
    description: "전구와 조명 부속을 볼 수 있는 상점",
    orderGuide: "전구 규격, 색온도, 연결 부속을 같이 확인하세요.",
    review: "전구를 찾을 때 참고할 수 있고, 응대가 좋다는 메모가 있습니다.",
    memo: "전구를 찾을 때 참고할 수 있고, 응대가 좋다는 메모가 있습니다.",
    tags: ["기타", "조명", "전구"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "baeksan-wood-veneer",
    type: "material",
    categories: ["wood"],
    name: "백산무늬목재",
    area: "을지로",
    address: "서울특별시 중구 을지로 170",
    phone: "02-2285-2800",
    description: "원목과 무늬목 종류가 많은 목재상",
    orderGuide: "재료 사진, 필요한 면적, 두께를 정리해 가면 좋습니다.",
    review: "원목 종류가 매우 많다는 메모가 있어 목재 탐색용으로 좋습니다.",
    memo: "원목 종류가 매우 많다는 메모가 있어 목재 탐색용으로 좋습니다.",
    tags: ["목재", "원목", "재료 구매 가능"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "woosung-trading",
    type: "material",
    categories: ["etc"],
    name: "우성상사",
    area: "을지로",
    address: "서울특별시 중구 을지로 203-1 1층",
    phone: "02-2265-1438",
    description: "실리콘과 레진을 저렴하게 보기 좋은 상점",
    orderGuide: "용도, 경화 방식, 필요한 양을 먼저 정리해 문의하세요.",
    review: "실리콘과 레진 쪽 메모가 강합니다.",
    memo: "실리콘과 레진 쪽 메모가 강합니다.",
    tags: ["기타", "레진", "실리콘"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "samik-electric",
    type: "material",
    categories: ["etc"],
    name: "삼익전기",
    area: "을지로",
    address: "서울특별시 종로구 장사동 204",
    phone: "02-2265-4080",
    description: "전기 관련 부속품을 보기 좋은 상점",
    orderGuide: "사용 전압, 연결 방식, 필요한 부속 사진을 준비하면 좋습니다.",
    review: "응대가 친절하다는 메모가 남아 있습니다.",
    memo: "응대가 친절하다는 메모가 남아 있습니다.",
    tags: ["기타", "전기 부속", "친절"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "taesung-bolt",
    type: "material",
    categories: ["etc"],
    name: "태성 볼트",
    area: "을지로",
    address: "서울특별시 중구 을지로3가 140-5 1층",
    phone: "02-2275-7589",
    description: "볼트와 너트를 소량으로 구매 가능",
    orderGuide: "볼트 규격, 길이, 수량을 적어두고 방문하세요.",
    review: "소량 판매가 가능한 점이 핵심입니다.",
    memo: "소량 판매가 가능한 점이 핵심입니다.",
    tags: ["기타", "볼트", "소량 가능"],
    verifiedAt: "2026-05-30",
    isVisible: true,
  },
  {
    id: "acrylic-choika",
    type: "material",
    categories: ["acrylic"],
    name: "아크릴최가",
    area: "을지로",
    address: "서울특별시 중구 마른내로 79 세운 푸르지오 헤리시티 B108호",
    phone: "02-2274-8404",
    extraContact: "02-2274-8405",
    description: "아크릴 원자재와 재단, 제작 상담이 가능한 전문 업체",
    memo: "CNC 절단과 UV 출력까지 함께 문의되는 편이라 작업 내용까지 같이 전달하는 편이 좋습니다.",
    tags: ["아크릴", "재단", "제작"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "hyundai-acrylic",
    type: "material",
    categories: ["acrylic"],
    name: "현대아크릴",
    area: "을지로",
    address: "서울특별시 중구 창경궁로 64 브라더빌딩",
    phone: "02-2272-9966",
    extraContact: "02-2266-8877",
    description: "아크릴 제작, 재단, 포맥스 가공을 함께 문의할 수 있는 상점",
    memo: "도면을 메일로 보내면 견적 상담이 빠르다고 안내하는 채널이 확인됩니다.",
    tags: ["아크릴", "포맥스", "재단"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "adwin-tech",
    type: "service",
    categories: ["laser-cutting"],
    name: "애드윈테크",
    area: "을지로",
    address: "서울특별시 중구 충무로 55",
    phone: "02-2277-8150",
    description: "UV 평판출력과 아크릴 가공을 함께 맡길 수 있는 출력 업체",
    memo: "아크릴 프린트 용도로 많이 찾는 편이라 출력물 크기와 재질을 같이 전달하는 편이 좋습니다.",
    tags: ["UV출력", "아크릴 프린트", "가공"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "samwoo-bolt",
    type: "material",
    categories: ["etc"],
    name: "삼우볼트상사",
    area: "을지로",
    address: "서울특별시 중구 을지로 155",
    phone: "02-2272-8436",
    description: "볼트, 너트, 와셔 등 체결 부품을 찾기 좋은 상점",
    memo: "을지로4가 쪽 볼트류 상점으로 함께 정리해 두기 좋습니다.",
    tags: ["볼트", "너트", "부자재"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "hyundai-bolt-department",
    type: "material",
    categories: ["etc"],
    name: "현대종합볼트백화점",
    area: "을지로",
    address: "서울특별시 중구 을지로30길 12",
    phone: "02-2265-2310",
    description: "희소 규격까지 찾기 쉬운 볼트 전문 상점",
    memo: "친절하다는 사용자 메모가 있어 우선 확인처로 남겨둡니다.",
    tags: ["볼트", "너트", "친절"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "ihwa-stainless",
    type: "material",
    categories: ["metal"],
    name: "이화스텐",
    area: "을지로",
    address: "서울특별시 중구 을지로19길 10",
    phone: "02-2274-3490",
    extraContact: "02-2274-3494",
    description: "스테인리스 봉과 판재 문의에 적합한 금속상",
    memo: "스텐 봉 재단 메모가 함께 전달된 곳입니다.",
    tags: ["스테인리스", "봉 재단", "금속"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "noroo-paint-euljiro",
    type: "material",
    categories: ["etc"],
    name: "노루페인트 을지로점",
    area: "을지로",
    address: "서울특별시 중구 을지로 127",
    phone: "02-2273-7404",
    description: "목재와 금속 마감용 페인트를 바로 확인할 수 있는 대리점",
    memo: "칼라메이트 을지로점으로도 확인되는 매장입니다.",
    tags: ["페인트", "도장", "색상 상담"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "benjamin-moore-nonhyeon",
    type: "material",
    categories: ["etc"],
    name: "벤자민무어페인트",
    area: "논현",
    address: "서울특별시 강남구 학동로 151",
    phone: "1577-3103",
    description: "페인트 컬러 상담과 샘플 확인에 적합한 쇼룸형 매장",
    memo: "논현 기준 컬러스테이션 매장으로 확인되는 곳입니다.",
    tags: ["페인트", "컬러 상담", "쇼룸"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "iveranda",
    type: "material",
    categories: ["wood"],
    name: "아이베란다",
    area: "경기 광주",
    address: "경기도 광주시 초월읍 용수길 42-19",
    phone: "031-769-1748",
    description: "목재와 DIY용 부자재를 폭넓게 찾을 수 있는 목재 쇼핑몰 겸 매장",
    memo: "서울권은 아니지만 목재, 철물, 공구를 한 번에 보기 쉬워 같이 정리했습니다.",
    tags: ["목재", "DIY", "부자재"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "daea-wooden",
    type: "material",
    categories: ["wood"],
    name: "대아우딘",
    area: "용인",
    address: "경기도 용인시 처인구 모현읍 포은대로 225-5",
    phone: "031-766-6266",
    description: "발크로멧과 컬러 MDF 계열 자재를 찾기 좋은 목재 업체",
    memo: "공개 주소는 포은대로 225-5, 구주소 표기는 매산리 26-14로 함께 확인됩니다.",
    tags: ["발크로멧", "컬러 MDF", "목재"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
  {
    id: "palpal-acrylic",
    type: "material",
    categories: ["acrylic"],
    name: "팔팔아크릴",
    area: "목포",
    address: "전라남도 목포시 동명로 6-1",
    phone: "061-274-5755",
    description: "아크릴 재단과 케이스 제작을 온라인으로도 맡길 수 있는 업체",
    memo: "서울권은 아니지만 재단 전문 업체로 자주 참고되는 편입니다.",
    tags: ["아크릴", "재단", "케이스 제작"],
    verifiedAt: "2026-06-17",
    isVisible: true,
  },
];

export const pendingLocationStores: PendingStore[] = [
  { name: "영동레이져땜", area: "종로", phone: "010-9251-5997", reason: "세부 주소 미확인" },
  { name: "주주레이저", area: "종로", phone: "010-7676-1753", reason: "세부 주소 미확인" },
  { name: "효성알미늄", area: "을지로", reason: "사용자 제보 주소와 사업자 주소가 달라 현재 위치 확인 필요" },
  { name: "우진정밀", area: "을지로", phone: "02-2279-4539", reason: "정확한 현재 주소 미확인" },
  { name: "심화페인트 서교대리점", area: "서교", reason: "상호명과 매장 정보 교차 확인 필요" },
  { name: "던에드워드", area: "서울", reason: "서울 매장 다수로 대상 지점 특정 필요" },
];

export function getCategoriesByMode(mode: ExploreMode) {
  return mode === "service" ? serviceCategories : materialCategories;
}

export function getCategoryLabel(categoryId: CategoryId) {
  return allCategories.find((category) => category.id === categoryId)?.label ?? categoryId;
}

function normalizeStoreName(name: string) {
  return name.trim().toLowerCase().replace(/\s+/g, "");
}

export function getVisibleStoreByName(name: string) {
  const target = normalizeStoreName(name);
  return stores.find((store) => store.isVisible && normalizeStoreName(store.name) === target) ?? null;
}
